kind: CronJob
apiVersion: batch/v1
metadata:
  name: minute-backup
  namespace: nginx

spec:
  schedule: "* * * * *"       # min, hour, day, day of week, day of month.
  jobTemplate:
    spec: 
      template:
        metadata:
          name: minute-backup
          labels:
            app: minute-backup
        spec:
          containers:
          - name: minute-backup-completion
            image: busybox:latest
            command: 
            - sh
            - -c
            - >
              echo "backup started" ;
              mkdir -p /backups && 
              mkdir -p /demo-data && 
              cp -r /demo-data /backups &&
              echo "backup completed" ;
            volumeMounts: 
              - name: data-volume
                mountPath: /demo-data
              - name: backup-volume
                mountPath: /backups
          restartPolicy: OnFailure
          volumes:
            - name: data-volume
              hostPath: 
                path: /demo-data
                type: DirectoryOrCreate
            - name: backup-volume
              hostPath: 
                path: /backups
                type: DirectoryOrCreate
            