apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apache-manager
  namespace: apache
rules:
  - apiGroups: ["", "apps", "rbac.authorization.k8s.io", "batch"] 
    resources: ["pods", "deployments", "services"]
    verbs: ["get", "delete", "watch", "list"]
