apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  nodeSelector:
    node-role: nginx-node   # this ensures it runs on the labeled node
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
